sudo: true
language: python
services:
  - docker
python:
  - 2.7
    #  - 3.4
  - 3.5
    #  - 3.6
os:
  - linux

before_install:
  - docker pull python:2.7
  - wget https://github.com/ohsu-comp-bio/funnel/releases/download/dev/funnel-linux-amd64.tar.gz
  - tar xfz funnel-linux-amd64.tar.gz -C /usr/bin
install:
  - pip install tox-travis
  - pip install nose
script: 
  - tox
  - nosetests -w ./cwltool-tes/tests
notifications:
  email: false
