sudo: true
language: python
services:
  - docker
python:
  - 2.7
    #  - 3.4
  - 3.5
    #  - 3.6
os:
  - linux
  
install:
  - pip install tox-travis
  - pip install -r ./cwltool-tes/tests/requirements.txt
before_script:
  - docker pull python:2.7
  - wget https://github.com/ohsu-comp-bio/funnel/releases/download/dev/funnel-linux-amd64.tar.gz -O /tmp/funnel-linux-amd64.tar.gz
  - tar xfz /tmp/funnel-linux-amd64.tar.gz
  - export PATH=$PATH:/tmp
script: 
  - tox
  - nosetests -w ./cwltool-tes/tests
notifications:
  email: false
